FrontBundle\Entity\Visita:
    type: entity
    table: null
    repositoryClass: FrontBundle\Repository\VisitaRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        data:
            type: string
            length: 255
    lifecycleCallbacks: {  }
