<?php

namespace FrontBundle\Repository;

/**
 * CentreMedicRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CentreMedicRepository extends \Doctrine\ORM\EntityRepository
{
}
