<?php

namespace FrontBundle\Repository;

/**
 * MetgeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MetgeRepository extends \Doctrine\ORM\EntityRepository
{
}
