<?php

namespace FrontBundle\Repository;

/**
 * PacientRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PacientRepository extends \Doctrine\ORM\EntityRepository
{
}
