<?php

namespace FrontBundle\Repository;

/**
 * VisitaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VisitaRepository extends \Doctrine\ORM\EntityRepository
{
}
